application: yhackertw92
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /game\.html
  static_files: game.html
  upload: game\.html

- url: /levelselect\.html
  static_files: levelselect.html
  upload: levelselect\.html

- url: /css
  static_dir: css 
- url: /img
  static_dir: img
- url: /js 
  static_dir: js
- url: /audio 
  static_dir: audio

- url: /login
  script: login.app

- url: /callback
  script: login.app

- url: /user
  script: login.app

- url: /test
  script: login.app

- url: /create
  script: comm.app

- url: /join
  script: comm.app

- url: /push
  script: comm.app

- url: /board
  script: comm.app

- url: /start
  script: comm.app

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
